# Define a function to update the prompt
setprompt() {
    export PS1="%n@%m %d > " # %d is the current directory in zsh
}

# Call the function to set the initial prompt
setprompt

# Override the 'cd' command with a function that changes directory and then updates the prompt
cd() {
    builtin cd "$@" && setprompt
}

# Pipeline - assuming you're setting up an environment variable or similar for zsh
# Check if the file exists before sourcing it
if [[ -f /Volumes/Build/github/pipeline/pipeline.sh ]]; then
    source /Volumes/Build/github/pipeline/pipeline.sh
else
    echo "pipeline.sh not found, skipping..."
fi